import Head from 'next/head'
import { useEffect, useState } from 'react'
import Post from '../components/Post'

export default function Home() {
  const [html, setHtml] = useState('');
  const fetchPost = async () => await fetch('/api/hello').then(e => e.json());

  useEffect(() => {
    fetchPost().then((response) => {
      setHtml(response.html)
    })
  }, []);
  return (
    <div>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {html &&
          <Post html={html} />
        }
      </main>

      <footer>
        Copyright 
      </footer>
    </div>
  )
}
